// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./src/components/DarkToggle.vue')['default']
    LangToggle: typeof import('./src/components/LangToggle.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
  }
}
